# Generated by Django 3.0.2 on 2020-06-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(default=0)),
                ('checked', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
