# Generated by Django 3.0.2 on 2020-06-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0003_auto_20200618_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='category',
        ),
        migrations.AddField(
            model_name='patient',
            name='category',
            field=models.ManyToManyField(related_name='_patient_category_+', to='consult.Patient'),
        ),
    ]
