# Generated by Django 3.0.2 on 2020-06-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0004_auto_20200618_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='category',
            field=models.ManyToManyField(to='consult.Field'),
        ),
    ]
