# Generated by Django 3.0.2 on 2020-06-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0005_auto_20200618_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='category',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
