# Generated by Django 3.0.2 on 2020-06-18 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0007_field_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.CharField(default='', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consult.Field')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consult.Patient')),
            ],
        ),
    ]
