# Generated by Django 3.0.2 on 2020-06-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0008_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
