# Generated by Django 3.0.2 on 2020-06-19 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='doctor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
    ]
